name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "1.22", "1.23"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Environment (go${{ matrix.go }})
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # managed by golangci-lint

      - name: Download Dependencies
        run: go mod download -x

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Test
        run: go test -v -race ./...
